import { useState } from 'react'
import Modal from './Modal'
import ModalSection from './ModalSection'
import { supabase } from '../lib/supabase'
import { friendlyError } from '../lib/errors'
import { useConfirm } from '../context/ConfirmContext'
import { modalFooter, secondaryButton } from '../lib/controlStyles'

// The link somebody subscribes their phone's calendar to.
//
// Not a download. A downloaded calendar is imported once and then sits there
// being wrong: the roster changes and their phone still shows last week, while
// looking perfectly correct. A subscription re-reads itself.
//
// The URL is the whole of the security, because a calendar app arrives with no
// login and nothing to be asked for one. So it is long, random, one per person,
// and it can be replaced, which is what to do when somebody loses a phone.
function makeToken() {
    // Two UUIDs with the dashes out. Longer than anything anybody is going to
    // guess, and generated by the browser's own random rather than by Math.
    return (crypto.randomUUID() + crypto.randomUUID()).replace(/-/g, '')
}

export default function CalendarLinkDialog({ employee, onClose, onChanged }) {
    const confirm = useConfirm()
    const [token, setToken] = useState(employee.calendar_token || '')
    const [busy, setBusy] = useState(false)
    const [error, setError] = useState('')
    const [copied, setCopied] = useState('')

    const base = import.meta.env.VITE_SUPABASE_URL || ''
    const url = token ? `${base}/functions/v1/roster-calendar?token=${token}` : ''

    async function save(next) {
        setBusy(true)
        setError('')
        const { error: err } = await supabase
            .from('employees')
            .update({ calendar_token: next })
            .eq('id', employee.id)

        setBusy(false)
        if (err) { setError(friendlyError(err)); return false }
        setToken(next)
        onChanged?.()
        return true
    }

    async function replace() {
        const ok = await confirm({
            title: `Make a new link for ${employee.full_name}?`,
            message: 'The one they have now stops working straight away and their calendar goes empty until they subscribe to the new one. This is what to do if a phone has been lost.',
            confirmLabel: 'Make a new one',
            tone: 'danger',
        })
        if (ok) save(makeToken())
    }

    function copy(text, what) {
        navigator.clipboard?.writeText(text)
        setCopied(what)
        setTimeout(() => setCopied(''), 2000)
    }

    // webcal:// is what tells a phone to subscribe rather than to download. The
    // plain address is there too, because that is the one Google's own
    // "add by URL" box wants.
    const webcal = url.replace(/^https?:\/\//, 'webcal://')

    return (
        <Modal title={`Calendar link, ${employee.full_name}`} onClose={onClose}>
            {!token ? (
                <ModalSection
                    title="No link yet"
                    description="Making one lets them subscribe their phone's calendar to their own shifts. It updates itself when you publish a week, so they never have to come back for it."
                >
                    <p className="text-sm text-muted mb-4">
                        Only their own shifts, and only the ones you have published. Nothing about
                        anybody else and nothing about pay.
                    </p>
                    <button
                        type="button"
                        onClick={() => save(makeToken())}
                        disabled={busy}
                        className="px-5 py-2.5 bg-accent text-white text-sm font-semibold rounded-lg hover:bg-orange-600 disabled:opacity-50"
                    >
                        {busy ? 'Making it...' : 'Make a link'}
                    </button>
                </ModalSection>
            ) : (
                <>
                    <ModalSection
                        title="Their link"
                        description="Send this to them once. Treat it like a password: anybody holding it can see this person's shifts."
                    >
                        <div className="bg-gray-50 border border-border rounded-lg p-3 mb-3">
                            <code className="text-xs text-gray-700 break-all">{url}</code>
                        </div>
                        <div className="flex flex-wrap gap-2">
                            <button
                                type="button"
                                onClick={() => copy(webcal, 'subscribe')}
                                className="px-4 py-2 bg-accent text-white text-sm font-semibold rounded-lg hover:bg-orange-600"
                            >
                                {copied === 'subscribe' ? 'Copied' : 'Copy for a phone'}
                            </button>
                            <button type="button" onClick={() => copy(url, 'plain')} className={secondaryButton}>
                                {copied === 'plain' ? 'Copied' : 'Copy the plain address'}
                            </button>
                        </div>
                    </ModalSection>

                    <ModalSection title="What to tell them">
                        <ul className="text-sm text-muted space-y-2">
                            <li>
                                <b className="text-gray-900">On an iPhone.</b> Open the link and it offers to
                                subscribe. Settings, Calendar, Accounts also has Add Subscribed Calendar.
                            </li>
                            <li>
                                <b className="text-gray-900">On Android.</b> Google Calendar on a computer,
                                Other calendars, then From URL, and paste the plain address. Phones cannot
                                add one, only the website can.
                            </li>
                            <li>
                                <b className="text-gray-900">It is not instant.</b> Their calendar re-reads it
                                on its own, but Apple checks more often than Google and Google can take most
                                of a day. Worth saying so once, or somebody will think it is broken.
                            </li>
                        </ul>
                    </ModalSection>

                    <ModalSection title="If a phone goes missing">
                        <p className="text-sm text-muted mb-3">
                            Making a new link stops the old one working straight away.
                        </p>
                        <button type="button" onClick={replace} disabled={busy} className={secondaryButton}>
                            Make a new link
                        </button>
                    </ModalSection>
                </>
            )}

            {error && <p className="mx-6 mb-4 text-sm text-red-700 bg-red-50 rounded-lg p-3">{error}</p>}

            <div className={modalFooter}>
                <button
                    type="button"
                    onClick={onClose}
                    className="px-4 py-2 border border-border text-gray-600 text-sm font-medium rounded-lg hover:bg-gray-50 bg-white"
                >
                    Done
                </button>
            </div>
        </Modal>
    )
}
